language: node_js
dist: trusty
node_js:
  - "6"
  - "8"
  - "10"
before_install:
  - npm install -g npm
  - npm install -g coveralls greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
   - make ci
after_script:
   - greenkeeper-lockfile-upload
notifications:
  irc: "chat.freenode.net#bucharest-gold"
after_success:
  - cat ./coverage/lcov.info | coveralls
